Starting
Traceback (most recent call last):
  File "/home/monaco/bt_analysis/code/LEIT-motifs/tests/extended_test.py", line 230, in <module>
    main()
  File "/home/monaco/bt_analysis/code/LEIT-motifs/tests/extended_test.py", line 112, in main
    motifs, num_dist = pmotif_findg(shm_ts.name, n, dimensions, windows[number_r], 1, dimensionality[number_r], r_vals_computed[number_r], 0.5, 200, K)
    ^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
/home/monaco/.local/share/uv/python/cpython-3.12.6-linux-x86_64-gnu/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
Starting
/home/monaco/.local/share/uv/python/cpython-3.12.6-linux-x86_64-gnu/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 5 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/home/monaco/.local/share/uv/python/cpython-3.12.6-linux-x86_64-gnu/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 401 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
